# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "30e8cd93bb7106a93d06f382c175a506"
application_url = "https://nandira-product-app.onrender.com"
embedded = true
name = "Product Manager - Nandira"
handle = "nandira-product-app"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://nandira-product-app.onrender.com/auth/callback",
  "https://nandira-product-app.onrender.com/auth/shopify/callback",
  "https://nandira-product-app.onrender.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "nandira-crisp.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
